In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

import torchvision
import torchvision.transforms as transforms

from Network import Network
from Network import Train
from Network import RunBuilder

from collections import OrderedDict

%load_ext nb_black

ModuleNotFoundError: No module named 'Network'

In [6]:
network = Network()
train_set = torchvision.datasets.FashionMNIST(
    root='./data/FashionMNIST',
    train=True,
    download=True,
    transform=transforms.Compose([transforms.ToTensor()])
)

# hyper parameters
parameters = OrderedDict(
    lr=[0.01],
    batch_size=[1000]
)
epochs = 10

print(RunBuilder.get_runs(parameters)[0])

Run(lr=0.01, batch_size=1000)


In [8]:
train = Train()
train.train_data_set(train_set, network, RunBuilder.get_runs(parameters)[0], epochs)

epoch: 0, total_correct: 36840, loss: 60.012859523296356
epoch: 1, total_correct: 46631, loss: 34.16014921665192
epoch: 2, total_correct: 49198, loss: 28.681873470544815
epoch: 3, total_correct: 50524, loss: 25.493580639362335
epoch: 4, total_correct: 51539, loss: 22.91268676519394
epoch: 5, total_correct: 52016, loss: 21.440648287534714
epoch: 6, total_correct: 52470, loss: 20.22565394639969
epoch: 7, total_correct: 52709, loss: 19.47569966316223
epoch: 8, total_correct: 53015, loss: 18.777490079402924
epoch: 9, total_correct: 53201, loss: 18.469931721687317


{'network': Network(
   (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
   (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
   (fc1): Linear(in_features=192, out_features=120, bias=True)
   (fc2): Linear(in_features=120, out_features=60, bias=True)
   (out): Linear(in_features=60, out_features=10, bias=True)
 )}

In [6]:
print(network.conv2.weight.grad.shape)

torch.Size([12, 6, 5, 5])


In [7]:
print(network.conv2.weight.grad)

tensor([[[[-6.7098e-03, -4.5789e-03,  1.6946e-04,  6.9232e-03, -9.2915e-03],
          [-7.9018e-03, -1.0894e-02, -4.1680e-03,  1.4388e-02, -4.1222e-03],
          [-9.7544e-03, -1.2610e-02, -2.0950e-03,  1.8964e-02, -6.8213e-04],
          [-8.8281e-03, -1.0421e-02, -4.1149e-03,  1.4172e-02, -1.2236e-03],
          [-1.2603e-02, -1.4072e-02, -9.3625e-03,  1.0288e-02, -4.9792e-03]],

         [[-6.6343e-03,  2.5021e-04,  2.5346e-03,  6.7442e-04,  2.0497e-04],
          [-1.7411e-03,  8.8103e-04,  3.3608e-03,  1.1769e-02,  7.4298e-04],
          [-1.3939e-03,  3.0312e-04,  1.0484e-02,  9.7927e-03, -5.3990e-03],
          [-2.2987e-03, -1.1330e-03,  7.8487e-03,  1.1059e-02,  3.0822e-03],
          [-1.6943e-03,  4.6953e-03,  1.5070e-02,  1.4371e-02, -1.6319e-03]],

         [[ 2.5773e-03,  4.7970e-03,  2.5810e-03, -1.4521e-02, -1.2960e-02],
          [ 2.6116e-03,  3.3473e-03, -4.1312e-03, -8.6579e-03, -1.3874e-03],
          [ 3.8331e-03,  5.2039e-03,  4.4339e-03, -1.7514e-03, -1.6855e-

In [8]:
print(network.conv2.weight.grad.shape)

torch.Size([12, 6, 5, 5])


In [9]:
print(network.conv2.weight.grad)

tensor([[[[-6.7098e-03, -4.5789e-03,  1.6946e-04,  6.9232e-03, -9.2915e-03],
          [-7.9018e-03, -1.0894e-02, -4.1680e-03,  1.4388e-02, -4.1222e-03],
          [-9.7544e-03, -1.2610e-02, -2.0950e-03,  1.8964e-02, -6.8213e-04],
          [-8.8281e-03, -1.0421e-02, -4.1149e-03,  1.4172e-02, -1.2236e-03],
          [-1.2603e-02, -1.4072e-02, -9.3625e-03,  1.0288e-02, -4.9792e-03]],

         [[-6.6343e-03,  2.5021e-04,  2.5346e-03,  6.7442e-04,  2.0497e-04],
          [-1.7411e-03,  8.8103e-04,  3.3608e-03,  1.1769e-02,  7.4298e-04],
          [-1.3939e-03,  3.0312e-04,  1.0484e-02,  9.7927e-03, -5.3990e-03],
          [-2.2987e-03, -1.1330e-03,  7.8487e-03,  1.1059e-02,  3.0822e-03],
          [-1.6943e-03,  4.6953e-03,  1.5070e-02,  1.4371e-02, -1.6319e-03]],

         [[ 2.5773e-03,  4.7970e-03,  2.5810e-03, -1.4521e-02, -1.2960e-02],
          [ 2.6116e-03,  3.3473e-03, -4.1312e-03, -8.6579e-03, -1.3874e-03],
          [ 3.8331e-03,  5.2039e-03,  4.4339e-03, -1.7514e-03, -1.6855e-

In [10]:
train_set.targets


tensor([9, 0, 0,  ..., 3, 0, 5])

In [11]:
train_set.targets.shape

torch.Size([60000])

In [12]:
print(network.conv2.weight.grad)


tensor([[[[-6.7098e-03, -4.5789e-03,  1.6946e-04,  6.9232e-03, -9.2915e-03],
          [-7.9018e-03, -1.0894e-02, -4.1680e-03,  1.4388e-02, -4.1222e-03],
          [-9.7544e-03, -1.2610e-02, -2.0950e-03,  1.8964e-02, -6.8213e-04],
          [-8.8281e-03, -1.0421e-02, -4.1149e-03,  1.4172e-02, -1.2236e-03],
          [-1.2603e-02, -1.4072e-02, -9.3625e-03,  1.0288e-02, -4.9792e-03]],

         [[-6.6343e-03,  2.5021e-04,  2.5346e-03,  6.7442e-04,  2.0497e-04],
          [-1.7411e-03,  8.8103e-04,  3.3608e-03,  1.1769e-02,  7.4298e-04],
          [-1.3939e-03,  3.0312e-04,  1.0484e-02,  9.7927e-03, -5.3990e-03],
          [-2.2987e-03, -1.1330e-03,  7.8487e-03,  1.1059e-02,  3.0822e-03],
          [-1.6943e-03,  4.6953e-03,  1.5070e-02,  1.4371e-02, -1.6319e-03]],

         [[ 2.5773e-03,  4.7970e-03,  2.5810e-03, -1.4521e-02, -1.2960e-02],
          [ 2.6116e-03,  3.3473e-03, -4.1312e-03, -8.6579e-03, -1.3874e-03],
          [ 3.8331e-03,  5.2039e-03,  4.4339e-03, -1.7514e-03, -1.6855e-

In [15]:
def get_all_preds(model, data_loader):
    all_preds = torch.tensor([])
    for batch in data_loader:
        images, labels = batch

        preds = model(images)
        all_preds = torch.cat((all_preds, preds), dim=0)

    return all_preds

pred_loader = torch.utils.data.DataLoader(train_set, batch_size=10000)
train_preds = get_all_preds(network, pred_loader)
print(train_preds)

tensor([[-17.4528, -15.9946, -13.5622,  ...,   3.1228,  -6.4522,  10.4567],
        [ 10.5093,  -7.1679,  -2.9810,  ..., -23.6375,  -8.6133, -18.4434],
        [  4.8236,   0.1962,  -0.7122,  ..., -12.9334,  -1.8881,  -8.9650],
        ...,
        [ -0.1679,   0.8697,  -0.5264,  ..., -17.0724,  -4.9605, -12.4725],
        [  4.7678,  -4.8439,   1.0673,  ...,  -9.9595,  -2.9163, -10.2133],
        [ -7.5611, -12.3472,  -8.2275,  ...,  -2.3840,  -5.4121,  -4.1972]], grad_fn=<CatBackward>)


In [16]:
print(train_preds.shape)

torch.Size([60000, 10])


In [22]:
train_preds.argmax(dim=1)

tensor([9, 0, 0,  ..., 3, 0, 5])

In [36]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(train_set.targets, train_preds.argmax(dim=1))

In [37]:
print(f"total loss test: {ret['total_loss']}")
print(f"correctly predicted: ret['total_correct']")
print(f"actual correct: {test_set.targets.shape}")
print(f"% correct: {ret['total_correct']}/{test_set.targets.shape}")

[[5638    4  102   79   10    2  110    0   55    0]
 [  32 5852    1   96    6    0    7    0    6    0]
 [  74    3 4872   68  693    0  246    0   42    2]
 [ 395   27   22 5403   94    0   55    0    4    0]
 [  21    8  352  355 4793    0  444    1   26    0]
 [   0    0    1    0    0 5702    1  166   36   94]
 [1768    9  741  142  400    0 2856    0   84    0]
 [   0    0    0    0    0   32    0 5789   34  145]
 [  26    3   15   45   25    1   22    2 5861    0]
 [   0    0    0    0    0   12    0  168    7 5813]]


In [38]:
print(f"total loss test: {ret['total_loss']}")
print(f"correctly predicted: {ret['total_correct']}")
print(f"actual correct: {test_set.targets.shape}")
print(f"% correct: {ret['total_correct']}/{test_set.targets.shape}")

SyntaxError: unexpected EOF while parsing (<ipython-input-16-48b0962e0649>, line 1)

In [19]:
test_set = torchvision.datasets.FashionMNIST(
    root='F_MNIST_data_test/', 
    download=True, 
    train=False,
    transform=transforms.Compose([transforms.ToTensor()])
)


In [20]:
test_set

Dataset FashionMNIST
    Number of datapoints: 10000
    Root location: F_MNIST_data_test/
    Split: Test
    StandardTransform
Transform: Compose(
               ToTensor()
           )

In [31]:
def test_data_set(test_set, network, run):
    final_tot_correct = []
    batch_size = run.batch_size
    lr = run.lr

    # set batch size
    data_loader = torch.utils.data.DataLoader(
        test_set, batch_size=batch_size, num_workers=1
    )

    # print(network.conv1.weight.grad.shape)
    # print(network.conv2.weight.grad.shape)

    # set optimizer - Adam
    optimizer = optim.Adam(network.parameters(), lr=lr)

    # start training
    total_loss = 0
    total_correct = 0

    for batch in data_loader:
        images, labels = batch

        # forward propagation
        preds = network(images)

        # estimate loss
        loss = F.cross_entropy(preds, labels)

        # zero out grads for every new iteration
        optimizer.zero_grad()

        # back propagation
        loss.backward()

        # update weights
        # w = w - lr * grad_dw
        optimizer.step()

        total_loss += loss.item()
        total_correct += preds.argmax(dim=1).eq(labels).sum().item()

    return {
        "network": network,
        "total_loss": total_loss,
        "total_correct": total_correct,
    }

<IPython.core.display.Javascript object>

In [32]:
ret = test_data_set(test_set, network, RunBuilder.get_runs(parameters)[0])
print(ret["total_loss"])
print(ret["total_correct"])

4.758265316486359
8292


<IPython.core.display.Javascript object>

In [35]:
print(test_set.targets.shape)

torch.Size([10000])


<IPython.core.display.Javascript object>

In [52]:
print(f"total loss test: {ret['total_loss']}")
print(f"correctly predicted: {ret['total_correct']}")
print(f"actual correct: {test_set.targets.numpy().shape[0]}")
print(f"% correct: {ret['total_correct']}/{test_set.targets.numpy().shape[0]}")
test_set.targets.numpy().shape[0]

total loss test: 4.758265316486359
correctly predicted: 8292
actual correct: 10000
% correct: 8292/10000


10000

<IPython.core.display.Javascript object>

In [3]:
train_set = torchvision.datasets.FashionMNIST(
    root='./data/FashionMNIST',
    train=True,
    download=True,
    transform=transforms.Compose([transforms.ToTensor()])
)

In [5]:
data_loader = torch.utils.data.DataLoader(
        train_set, batch_size=100, num_workers=1
    )

In [8]:
batch = next(iter(data_loader))
images, labels = batch

In [9]:
images

tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        ...,


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0.

In [10]:
images.shape

torch.Size([100, 1, 28, 28])

In [12]:
labels.shape

torch.Size([100])

In [13]:
train_set.targets.shape

torch.Size([60000])